version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: helpcenterhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Caminho para seu script SQL
volumes:
  db-data:
